### PR TITLE
Write unit/integration tests again (and fix failed code)

### LINKED ISSUE #33: Write unit/integration tests
~~TODO: Put memo text content here~~
see test files :p

### PR DESCRIPTION
**Pull request by tyru**
Fix #33

### CODE REVIEW

**Comment by tyru** [comment]
All tests should pass if #90 is reverted?

File: cmd/add.go [hunk 1]
```diff
@@ -102,6 +107,25 @@ func (cmd *addCmd) doAdd(from, reposPath string) error {
 		return errors.New("the repository already exists: " + reposPath)
 	}
 
+	reposType, err := cmd.detectReposType(dst)
+	if err != nil {
+		return err
+	}
+
+	// Check if regular files exist
```
Comment (tyru) [inline cmd/add.go]: s/regular/irregular/
